#!/usr/bin/env sh
 
# Import required Functions and Parameters
if [ -f ~/.config/bspwm/src/bspwmrc.sh ] ; then
  . ~/.config/bspwm/src/bspwmrc.sh
fi
 
bspc monitor -d I II III IV V VI VII VIII IX X
 
bspc config border_width         2
bspc config window_gap          12
 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
 
# No Windows Border
bspc config border_width 0
 
# VMWare Bidirectional Clipboard
vmware-user-suid-wrapper &
 
# Sxhkd Init
checkProcess sxhkd || launchProcess sxhkd
 
# Polybar Init
checkProcess polybar || { launchProcess "$_pbl" ; unset -v -- _pbl ; }
 
# Picom Init
checkProcess picom || launchProcess picom
 
# Feh Init (Desktop Wallpaper)
/usr/bin/feh --bg-fill /home/al3xbb/Desktop/4l3xBB/Wallpapers/Fondo.jpg &

# Avoid Compatibility errors with Java applications (Burpsuite...)
# Change the Windows Manager Name from bspwm to LG3D (Only the name)
wmname LG3D &
